development:
  adapter: postgresql
  encoding: utf8
  database: fincollegeapp_development
  pool: 5
  username: root
  password: password

test:
  adapter: postgresql
  database: fincollegeapp_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fincollegeapp_production
  pool: 5
  timeout: 5000
