development:
  adapter: postgresql
  encoding: utf8
  database: theveterinarians_development
  pool: 5
  username: root
  password: password

test:
  adapter: postgresql
  database: theveterinarians_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: theveterinarians_production
  pool: 5
  timeout: 5000
